# Generated by Django 5.2 on 2025-06-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projectattachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectAttachment',
        ),
    ]
