# Generated by Django 5.2 on 2025-06-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_project_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='attachments',
        ),
    ]
