# Generated by Django 5.2 on 2025-06-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_project_attachments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='colors',
            new_name='color',
        ),
    ]
