# Generated by Django 5.2 on 2025-06-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_friendrequest_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
